// Side-effect imports: each module registers resolvers and routes.
import './resources/posts.js'
import './media/routes.js'
import './views/index.js'
import './studios/index.js'
import './library/index.js'
import './live/index.js'
import './dashboard/index.js'
import './safety/index.js'
import './social/index.js'
import './drops/index.js'
import './boards/index.js'
import './reads/index.js'
